import type { Metadata } from 'next'
// import { ThemeProvider } from '@/components/theme-provider'
import TopBar from '@/components/TopBar'
import LeftBar from '@/components/LeftBar'
import BottomBar from '@/components/BottomBar'

export const metadata: Metadata = {
  title: 'SocialGramm ',
  description: 'Generated by create next app',
}

export default function PagesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <div className='flex flex-col md:flex-row h-screen'>
      <TopBar />
      <LeftBar />
      {children}  
      <BottomBar />
    </div>
  )
}
